/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _snap_empty_h_
#define _snap_empty_h_
//---------------------------------------------------------------------------------
extern const unsigned char snap_empty[];
extern const int snap_empty_size;
//---------------------------------------------------------------------------------
#endif //_snap_empty_h_
//---------------------------------------------------------------------------------
